//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Utils
{
	public static class TextUtils
	{
		public static bool isUAlpha(char c){
			return c >= 'A' && c <= 'Z';
		}
		
		public static bool isLAlpha(char c){
			return c >= 'a' && c <= 'z';
		}
		 
		public static bool isAlpha(char c){
			return (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z');
		}
	}
}

